name: Deploy docker container to aws ec2

on:
    push:
        branches: [main]

permissions:
    contents: read

jobs:
    ec2-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the files
              uses: actions/checkout@v3

            - id: deploy
              name: Deploy to ec2
              uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.8
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
                  aws_default_region: us-east-1
                  checkout: false
                  app_port: 3333
